"""
This is the hangman WORD GUESS  game.
In the game of Hangman, a  word is given/generated by the program and that word the player has to guess, letter by letter. 
The player guesses one letter at a time until the entire word has been guessed
"""
import random, sys

"""
This functio is to generate a defalt word from words available in a file
"""
def word_generate(file_name):
	with open(file_name) as file:
		content = file.read()
		word_list = content.splitlines()
		position = random.randint(0,len(word_list))
		return word_list[position]


"""
Game Logic
"""

GEN_WORD = word_generate('word_file.txt') #pass the file name where you have the all the words.
print(GEN_WORD)                           #comment this out as we dont want to disclose the computer generated random word

my_word = []
#attempt = 0 '''It is counting total attempts if you initialise here. so moved it to for loop below, where it resets to Zero for each letter.
guess_count = 0

for i in range(len(GEN_WORD)):
	attempt = 0

	while True:
		if guess_count == 6: #User has give only only chnaces to guess the word, so as soon as he reches 6 tries program quits
			print('You lost the Guess Game')
			sys.exit('Exeeding maximum tries, so quitting the script') #You can pass any message you want to display when script exits

		print(f'you have only {6 - guess_count} tries left:')
		LETTER = input(f'Enter your guess letter-{i+1}: ')
		attempt += 1

		if LETTER == GEN_WORD[i]:
			print(F'Guess Correct, you took {attempt} attempts for letter-{i+1}')
			my_word.append(LETTER)
			break
		else:
			guess_count += 1

GUESS_WORD = ''.join(my_word)

print(f'System generated random word is: {GEN_WORD}')
print(f'your guess word is word is: {GUESS_WORD}')
print('You Won the Guess Game')




